spring:
  datasource:
    url: jdbc:postgresql://nozomi.proxy.rlwy.net:14929/railway
    username: postgres
    password: lzzyJYBxQtKoAEZCxIcNlDSepTboEyTM
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    hibernate:
      ddl-auto: update
